[package]
name = "srsrssrsbot"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

[dependencies]
grammers-client = { path = "../grammers/lib/grammers-client" }
reqwest = "0.11.0"
feed-rs = "0.5.1"
tokio = { version = "1.2.0", features = ["full"] }
